#remote_theme: pages-themes/cayman@v0.2.0
#description: "This is my personal CV for all possible employers to have a look at"
#title: "Digital CV of Philipp Korn"
#remote_theme: pages-themes/minimal@v0.2.0
#email: "philippkorn@posteo.de"
#phone: "+49 176 32584904"
#mastodon: "https://merveilles.town/@huxel"
